# ============================================================
# ENTRY POINT
# ============================================================
source-file ~/dotfiles/.config/tmux/options.conf
source-file ~/dotfiles/.config/tmux/keybinds.conf
source-file ~/dotfiles/.config/tmux/statusbar.conf

# ============================================================
# RELOAD CONFIG
# ============================================================
bind e source-file ~/dotfiles/.config/tmux/tmux.conf \; display "Config reloaded!"
